### ISSUE TITLE
SWTError: No more handles [gtk_init_check() failed]

### ISSUE THREAD

**Issue by elvisoliveira** [flathub/com.syntevo.SmartGit#37]
Arch Linux x86_64
Flatpak 1.8.1

user@archlinux ~> flatpak run -v com.syntevo.SmartGit
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 2801832527
F: Allocated instance id 2615880716
F: Add defaults in dir /com/syntevo/SmartGit/
F: Add locks in dir /com/syntevo/SmartGit/
F: Allowing dri access
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing session-dbus access
F: Allowing system-dbus access
F: Running 'bwrap --args 33 xdg-dbus-proxy --args=35'
F: Running 'bwrap --args 33 smartgit'
No protocol specified
Error invoking SmartGit
java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.syntevo.QBootLoader.main(SourceFile:111)
Caused by: org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
    at org.eclipse.swt.SWT.error(SWT.java:4750)
    at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1130)
    at org.eclipse.swt.widgets.Display.create(Display.java:1070)
    at org.eclipse.swt.graphics.Device.<init>(Device.java:175)
    at org.eclipse.swt.widgets.Display.<init>(Display.java:636)
    at org.eclipse.swt.widgets.Display.<init>(Display.java:627)
    at smartgit.Wy.a(SourceFile:117)
    at com.syntevo.sc.application.i.a(SourceFile:148)
    at com.syntevo.smartgit.n.a(SourceFile:321)
    at com.syntevo.smartgit.n.a(SourceFile:248)
    at com.syntevo.sc.application.F.b(SourceFile:69)
    at com.syntevo.smartgit.SmartGit.main(SourceFile:11)

**Comment by elvisoliveira** [comment]
xorg-server 1.20.8-3
i3-gaps 4.18.2-2

I just installed and executed, it was literally:
flatpak install flathub com.syntevo.SmartGit
flatpak run -v com.syntevo.SmartGit

This is the only package that does not work. I installed Eclise IDE using flathub flatpak and it works without any issues

**Comment by elvisoliveira** [comment]
[log.txt](https://github.com/flathub/com.syntevo.SmartGit/files/5114549/log.txt)

${HOME}/.var/app/com.syntevo.SmartGit/config/smartgit/20.1/logs

**Comment by x80486** [comment]
I installed the i3-based desktop (in a VM using `Boxes`) and the Flatpak runs fine; I'm aware it might not be exactly the same, but it should be quite close to what you have installed.

A little bit unrelated: are you able to run the official `tat.gz` package?

**Comment by elvisoliveira** [comment]
Yes. The AUR works and downloading the package from syntevo website also works

**Comment by x80486** [comment]
The runtime was updated to `20.08`. I have no idea how could that make a difference, but I think you might want to give it a whirl.
