### ISSUE TITLE
Crash at start after update to version 23.1 on Ubuntu with Wayland.

### ISSUE THREAD

**Issue by alemuntoni** [flathub/com.syntevo.SmartGit#97]
After updating to the latest version, I cannot launch SmartGit anymore.

I am running Ubuntu 22.04 with Wayland. If I start the session with X.org, it works.

This is the error I get when running SmartGit from Wayland:
```
flatpak run com.syntevo.SmartGit
If you experience strange GUI bugs or crashes, try setting GTK_THEME=Adwaita.
Error invoking SmartGit
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.syntevo.QBootLoader.main(SourceFile:113)
Caused by: org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4944)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:1199)
	at org.eclipse.swt.widgets.Display.create(Display.java:1123)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:167)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:632)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:623)
	at smartgit.GZ.a(SourceFile:57)
	at smartgit.aaT.a(SourceFile:196)
	at com.syntevo.smartgit.r.a(SourceFile:399)
	at com.syntevo.smartgit.r.a(SourceFile:293)
	at smartgit.aby.b(SourceFile:58)
	at com.syntevo.smartgit.SmartGit.main(SourceFile:9)
	... 5 more
```

I also cannot rollback to the previous version due to #94.

The official binaries downloaded from the syntevo website work as expected on Wayland.

**Comment by x80486** [comment]
Actually, I tested this in `Ubuntu 23.x`, but looks like `socket=wayland` might be causing the issue.
